### PR TITLE
Made project links more overt buttons

### PR DESCRIPTION
**Pull request by ShanTulshi**
Addresses #94 

- cleaned up gallery icons and renamed classes so `gallery` and `project` styles don't conflict
- changed gallery icon color to `dark-background-color` for consistency
- added text and fill to project page buttons to make them more obvious

### CODE REVIEW

**Comment by ShanTulshi** [comment]
The main thing I'm not sure about on this one is whether the `hover` animation is obvious enough, and what I can do to make it more so. The default underline looks ugly with the icons, so I disabled that.

**Comment by jasmine1996** [comment]
Hmm yeah they kind of look like tags to me. Also not sure about using buttons for external links
How about showing them as plain links instead of like buttons?
screenshot 2019-03-03 21 56 07

**Comment by ShanTulshi** [comment]
I made that change at SHA 64bfa46, but I'm not sure how I feel about the change. Here's pictures for comparison:

Before:
image

After:
image

**Comment by ShanTulshi** [comment]
Also, how do you feel about rounded buttons? I asked a couple of people and got conflicting responses about what works best. 
image

I'll put this in another branch, you can view it here: de9f5c4

**Comment by jasmine1996** [comment]
In general I'd avoid using buttons for pure links because buttons imply changing something or performing some action on the page (but it makes perfect sense for download).
But between the two styles for the buttons I like rounded corners better. Add a bit more padding to the left of the text to make it look more balanced.

**Comment by ShanTulshi** [comment]
Here's what it looks like now:
image

**Comment by jasmine1996** [comment]
For some reason the icons look a lot higher up on my laptop.
screenshot 2019-03-07 19 56 01
I tried applying `transform: translate(0, 0.2em)` to get them to look more aligned
screenshot 2019-03-07 19 57 51

**Comment by ShanTulshi** [comment]
@jasmine1996 interesting, it looks like the left side of the icon is cut off for you as well. I'll take a look.

**Comment by andrewipark** [comment]
can we get browser information @jasmine1996 ?

**Comment by jasmine1996** [comment]
> can we get browser information @jasmine1996 ?

I was running it on Chrome on Windows. The font was Segoe UI

**Pull request merged**
