### PR TITLE
Initial change on the navigation bar and increase max-width to 960px

### PR DESCRIPTION
**Pull request by tojason**
I will describe more detail soon!

### CODE REVIEW

**Comment by ShanTulshi** [comment]
@tojason can you define the colors you used as variables defined in `_sass/minima.scss`?

**Comment by andrewipark** [comment]
Did the crux of this change (max width) make it into master already?

**Comment by ShanTulshi** [comment]
It also has homepage changes that are still WIP

**Comment by ShanTulshi** [comment]
Removed `custom-css` in the last commit, this might be a breaking change. Partially addresses #74

**Pull request merged**
